// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/weplanx/utils/resources"
	"github.com/weplanx/utils/sessions"
	"github.com/weplanx/utils/values"
	"server/admin"
	index2 "server/admin/index"
	"server/admin/tencent"
	"server/api"
	"server/api/index"
	"server/common"
)

// Injectors from wire.go:

func InitializeAPI(values *common.Values) (*api.API, error) {
	client, err := UseMongoDB(values)
	if err != nil {
		return nil, err
	}
	database := UseDatabase(values, client)
	redisClient, err := UseRedis(values)
	if err != nil {
		return nil, err
	}
	conn, err := UseNats(values)
	if err != nil {
		return nil, err
	}
	jetStreamContext, err := UseJetStream(conn)
	if err != nil {
		return nil, err
	}
	keyValue, err := UseKeyValue(values, jetStreamContext)
	if err != nil {
		return nil, err
	}
	inject := &common.Inject{
		V:    values,
		Mgo:  client,
		Db:   database,
		RDb:  redisClient,
		Nats: conn,
		Js:   jetStreamContext,
		Kv:   keyValue,
	}
	hertz, err := UseApi(values)
	if err != nil {
		return nil, err
	}
	service := &index.Service{
		Inject: inject,
	}
	controller := &index.Controller{
		Service: service,
	}
	apiAPI := &api.API{
		Inject: inject,
		Hertz:  hertz,
		Index:  controller,
	}
	return apiAPI, nil
}

func InitializeAdmin(values2 *common.Values) (*admin.API, error) {
	client, err := UseMongoDB(values2)
	if err != nil {
		return nil, err
	}
	database := UseDatabase(values2, client)
	redisClient, err := UseRedis(values2)
	if err != nil {
		return nil, err
	}
	conn, err := UseNats(values2)
	if err != nil {
		return nil, err
	}
	jetStreamContext, err := UseJetStream(conn)
	if err != nil {
		return nil, err
	}
	keyValue, err := UseKeyValue(values2, jetStreamContext)
	if err != nil {
		return nil, err
	}
	inject := &common.Inject{
		V:    values2,
		Mgo:  client,
		Db:   database,
		RDb:  redisClient,
		Nats: conn,
		Js:   jetStreamContext,
		Kv:   keyValue,
	}
	hertz, err := UseAdmin(values2)
	if err != nil {
		return nil, err
	}
	csrf := UseCsrf(values2)
	transfer, err := UseTransfer(values2, jetStreamContext)
	if err != nil {
		return nil, err
	}
	service := UseValues(values2, keyValue)
	controller := &values.Controller{
		Service: service,
	}
	sessionsService := UseSessions(values2, redisClient)
	sessionsController := &sessions.Controller{
		Service: sessionsService,
	}
	resourcesService, err := UseResources(values2, client, database, redisClient)
	if err != nil {
		return nil, err
	}
	resourcesController := &resources.Controller{
		Service: resourcesService,
	}
	passport := UsePassport(values2)
	locker := UseLocker(values2, redisClient)
	captcha := UseCaptcha(values2, redisClient)
	indexService := &index2.Service{
		Inject:   inject,
		Passport: passport,
		Locker:   locker,
		Captcha:  captcha,
		Sessions: sessionsService,
	}
	indexController := &index2.Controller{
		Service: indexService,
		Csrf:    csrf,
		Values:  values2,
	}
	tencentService := &tencent.Service{
		Inject: inject,
	}
	tencentController := &tencent.Controller{
		Service: tencentService,
	}
	adminAPI := &admin.API{
		Inject:    inject,
		Hertz:     hertz,
		Csrf:      csrf,
		Transfer:  transfer,
		Values:    controller,
		Sessions:  sessionsController,
		Resources: resourcesController,
		Index:     indexController,
		Tencent:   tencentController,
	}
	return adminAPI, nil
}
